In [1]:
import pandas as pd
import os

# Define the path to the general folder
general_folder_path = '/Users/proxim/PROXIM/PROJECTS/olympics2024-analysis/data/CSV_files/general'

# List of CSV files in the general folder
general_files = [
    'athletes.csv', 'coaches.csv', 'events.csv', 'medallists.csv', 'medals_total.csv', 'medals.csv',
    'nocs.csv', 'schedules_preliminary.csv', 'schedules.csv', 'teams.csv', 'technical_officials.csv',
    'torch_route.csv', 'venues.csv'
]

# Load and display the structure of each CSV file in the general folder
for file in general_files:
    file_path = os.path.join(general_folder_path, file)
    df = pd.read_csv(file_path)
    print(f"File: {file}")
    print("Columns:", df.columns.tolist())
    print("First 5 rows:")
    print(df.head())
    print("\n")

File: athletes.csv
Columns: ['code', 'current', 'name', 'name_short', 'name_tv', 'gender', 'function', 'country_code', 'country', 'country_long', 'nationality', 'nationality_long', 'nationality_code', 'height', 'weight', 'disciplines', 'events', 'birth_date', 'birth_place', 'birth_country', 'residence_place', 'residence_country', 'nickname', 'hobbies', 'occupation', 'education', 'family', 'lang', 'coach', 'reason', 'hero', 'influence', 'philosophy', 'sporting_relatives', 'ritual', 'other_sports']
First 5 rows:
      code  current               name     name_short            name_tv  \
0  1532872     True   ALEKSANYAN Artur   ALEKSANYAN A   Artur ALEKSANYAN
1  1532873     True     AMOYAN Malkhas       AMOYAN M     Malkhas AMOYAN
2  1532874     True    GALSTYAN Slavik     GALSTYAN S    Slavik GALSTYAN
3  1532944     True  HARUTYUNYAN Arsen  HARUTYUNYAN A  Arsen HARUTYUNYAN
4  1532945     True    TEVANYAN Vazgen     TEVANYAN V    Vazgen TEVANYAN

  gender function country_code  country country_long  ...  \
0   Male  Athlete          ARM  Armenia      Armenia  ...
1   Male  Athlete          ARM  Armenia      Armenia  ...
2   Male  Athlete          ARM  Armenia      Armenia  ...
3   Male  Athlete          ARM  Armenia      Armenia  ...
4   Male  Athlete          ARM  Armenia      Armenia  ...

                                              family  \
0                          Father, Gevorg Aleksanyan
1                                                NaN
2                                                NaN
3  Wife, Diana (married October 2022). Daughter, ...
4                 Wife, Sona (married November 2023)

                         lang  \
0  Armenian, English, Russian
1                    Armenian
2                    Armenian
3                    Armenian
4           Armenian, Russian

                                               coach  \
0                    Gevorg Aleksanyan (ARM), father
1                                                NaN
2  Personal: Martin Alekhanyan (ARM).<br>National...
3                      National: Habetnak Kurghinyan
4                National: Habetnak Kurghinyan (ARM)

                                              reason  \
0  He followed his father and his uncle into the ...
1                                                NaN
2                                                NaN
3  While doing karate he noticed wrestlers traini...
4  “My family did not like wrestling very much. A...

                                                hero  \
0  Footballer Zinedine Zidane (FRA), World Cup wi...
1                                                NaN
2                                                NaN
3  Wrestler Armen Nazaryan (ARM, BUL), two-time O...
4                                                NaN

                       influence  \
0  His father, Gevorg Aleksanyan
1                            NaN
2                            NaN
3                            NaN
4                            NaN

                                          philosophy  \
0  "Wrestling is my life." (mediamax.am. 18 May 2...
1  "To become a good athlete, you first have to b...
2                                                NaN
3  “Nothing is impossible, set goals in front of ...
4                                                NaN

                                  sporting_relatives ritual other_sports
0                                                NaN    NaN          NaN
1  Uncle, Roman Amoyan (wrestling), 2008 Olympic ...    NaN          NaN
2                                                NaN    NaN          NaN
3                                                NaN    NaN          NaN
4                                                NaN    NaN          NaN

[5 rows x 36 columns]


File: coaches.csv
Columns: ['code', 'current', 'name', 'gender', 'function', 'category', 'country_code', 'country', 'country_long', 'disciplines', 'events', 'birth_date']
First 5 rows:
      code  current                 name  gender    function category  \
0  1533246     True       PEDRERO Ofelia  Female       Coach        C
1  1535775     True     RADHI SHENAISHIL    Male  Head Coach        C
2  1536055     True  AFLAKIKHAMSEH Majid    Male       Coach        C
3  1536059     True      YOUSEFY Mehrdad    Male       Coach        C
4  1536060     True         MADDAH Minoo  Female       Coach        C

  country_code  country              country_long        disciplines events  \
0          MEX   Mexico                    Mexico  Artistic Swimming   Team
1          IRQ     Iraq                      Iraq           Football    Men
2          IRI  IR Iran  Islamic Republic of Iran          Taekwondo    NaN
3          IRI  IR Iran  Islamic Republic of Iran          Taekwondo    NaN
4          IRI  IR Iran  Islamic Republic of Iran          Taekwondo    NaN

   birth_date
0  1988-03-28
1  1965-07-01
2  1973-08-26
3  1972-06-12
4  1976-05-17


File: events.csv
Columns: ['event', 'tag', 'sport', 'sport_code', 'sport_url']
First 5 rows:
                event      tag    sport sport_code  \
0    Men's Individual  archery  Archery        ARC
1  Women's Individual  archery  Archery        ARC
2          Men's Team  archery  Archery        ARC
3        Women's Team  archery  Archery        ARC
4          Mixed Team  archery  Archery        ARC

                                           sport_url
0  https://olympics.com/en/paris-2024/sports/archery
1  https://olympics.com/en/paris-2024/sports/archery
2  https://olympics.com/en/paris-2024/sports/archery
3  https://olympics.com/en/paris-2024/sports/archery
4  https://olympics.com/en/paris-2024/sports/archery


File: medallists.csv
Columns: ['medal_date', 'medal_type', 'medal_code', 'name', 'gender', 'country_code', 'country', 'country_long', 'nationality_code', 'nationality', 'nationality_long', 'team', 'team_gender', 'discipline', 'event', 'event_type', 'url_event', 'birth_date', 'code_athlete', 'code_team', 'is_medallist']
First 5 rows:
   medal_date    medal_type  medal_code             name  gender country_code  \
0  2024-07-27    Gold Medal         1.0  EVENEPOEL Remco    Male          BEL
1  2024-07-27  Silver Medal         2.0    GANNA Filippo    Male          ITA
2  2024-07-27  Bronze Medal         3.0    van AERT Wout    Male          BEL
3  2024-07-27    Gold Medal         1.0      BROWN Grace  Female          AUS
4  2024-07-27  Silver Medal         2.0   HENDERSON Anna  Female          GBR

         country   country_long nationality_code    nationality  ... team  \
0        Belgium        Belgium              BEL        Belgium  ...  NaN
1          Italy          Italy              ITA          Italy  ...  NaN
2        Belgium        Belgium              BEL        Belgium  ...  NaN
3      Australia      Australia              AUS      Australia  ...  NaN
4  Great Britain  Great Britain              GBR  Great Britain  ...  NaN

  team_gender    discipline                          event event_type  \
0         NaN  Cycling Road    Men's Individual Time Trial        ATH
1         NaN  Cycling Road    Men's Individual Time Trial        ATH
2         NaN  Cycling Road    Men's Individual Time Trial        ATH
3         NaN  Cycling Road  Women's Individual Time Trial        ATH
4         NaN  Cycling Road  Women's Individual Time Trial        ATH

                                           url_event  birth_date code_athlete  \
0  /en/paris-2024/results/cycling-road/men-s-indi...  2000-01-25      1903136
1  /en/paris-2024/results/cycling-road/men-s-indi...  1996-07-25      1923520
2  /en/paris-2024/results/cycling-road/men-s-indi...  1994-09-15      1903147
3  /en/paris-2024/results/cycling-road/women-s-in...  1992-07-07      1940173
4  /en/paris-2024/results/cycling-road/women-s-in...  1998-11-14      1912525

   code_team is_medallist
0        NaN         True
1        NaN         True
2        NaN         True
3        NaN         True
4        NaN         True

[5 rows x 21 columns]


File: medals_total.csv
Columns: ['country_code', 'country', 'country_long', 'Gold Medal', 'Silver Medal', 'Bronze Medal', 'Total']
First 5 rows:
  country_code        country                country_long  Gold Medal  \
0          USA  United States    United States of America          40
1          CHN          China  People's Republic of China          40
2          JPN          Japan                       Japan          20
3          AUS      Australia                   Australia          18
4          FRA         France                      France          16

   Silver Medal  Bronze Medal  Total
0            44            42    126
1            27            24     91
2            12            13     45
3            19            16     53
4            26            22     64


File: medals.csv
Columns: ['medal_type', 'medal_code', 'medal_date', 'name', 'gender', 'discipline', 'event', 'event_type', 'url_event', 'code', 'country_code', 'country', 'country_long']
First 5 rows:
     medal_type  medal_code  medal_date             name gender    discipline  \
0    Gold Medal         1.0  2024-07-27  Remco EVENEPOEL      M  Cycling Road
1  Silver Medal         2.0  2024-07-27    Filippo GANNA      M  Cycling Road
2  Bronze Medal         3.0  2024-07-27    Wout van AERT      M  Cycling Road
3    Gold Medal         1.0  2024-07-27      Grace BROWN      W  Cycling Road
4  Silver Medal         2.0  2024-07-27   Anna HENDERSON      W  Cycling Road

                           event event_type  \
0    Men's Individual Time Trial        ATH
1    Men's Individual Time Trial        ATH
2    Men's Individual Time Trial        ATH
3  Women's Individual Time Trial        ATH
4  Women's Individual Time Trial        ATH

                                           url_event     code country_code  \
0  /en/paris-2024/results/cycling-road/men-s-indi...  1903136          BEL
1  /en/paris-2024/results/cycling-road/men-s-indi...  1923520          ITA
2  /en/paris-2024/results/cycling-road/men-s-indi...  1903147          BEL
3  /en/paris-2024/results/cycling-road/women-s-in...  1940173          AUS
4  /en/paris-2024/results/cycling-road/women-s-in...  1912525          GBR

         country   country_long
0        Belgium        Belgium
1          Italy          Italy
2        Belgium        Belgium
3      Australia      Australia
4  Great Britain  Great Britain


File: nocs.csv
Columns: ['code', 'country', 'country_long', 'tag', 'note']
First 5 rows:
  code               country          country_long                   tag note
0  AFG           Afghanistan           Afghanistan           afghanistan    P
1  AHO  Netherlands Antilles  Netherlands Antilles  netherlands-antilles    H
2  AIN                   AIN                   AIN                   ain    P
3  ALB               Albania               Albania               albania    P
4  ALG               Algeria               Algeria               algeria    P


File: schedules_preliminary.csv
Columns: ['date_start_utc', 'date_end_utc', 'estimated', 'estimated_start', 'start_text', 'medal', 'venue_code', 'description', 'venue_code_other', 'discription_other', 'team_1_code', 'team_1', 'team_2_code', 'team_2', 'tag', 'sport', 'sport_code', 'sport_url']
First 5 rows:
         date_start_utc          date_end_utc  estimated  estimated_start  \
0  2024-07-25T07:30:00Z  2024-07-25T10:30:00Z      False            False
1  2024-07-25T12:15:00Z  2024-07-25T15:15:00Z      False            False
2  2024-07-28T07:30:00Z  2024-07-28T09:00:00Z      False            False
3  2024-07-28T12:15:00Z  2024-07-28T12:38:00Z      False            False
4  2024-07-28T13:47:00Z  2024-07-28T14:10:00Z      False            False

  start_text  medal venue_code description venue_code_other discription_other  \
0        NaN    NaN        INV   Invalides              NaN               NaN
1        NaN    NaN        INV   Invalides              NaN               NaN
2        NaN    NaN        INV   Invalides              NaN               NaN
3        NaN    NaN        INV   Invalides              NaN               NaN
4        NaN    NaN        INV   Invalides              NaN               NaN

  team_1_code team_1 team_2_code team_2      tag    sport sport_code  \
0         NaN    NaN         NaN    NaN  archery  Archery        ARC
1         NaN    NaN         NaN    NaN  archery  Archery        ARC
2         NaN    NaN         NaN    NaN  archery  Archery        ARC
3         NaN    NaN         NaN    NaN  archery  Archery        ARC
4         NaN    NaN         NaN    NaN  archery  Archery        ARC

                                           sport_url
0  https://olympics.com/en/paris-2024/sports/archery
1  https://olympics.com/en/paris-2024/sports/archery
2  https://olympics.com/en/paris-2024/sports/archery
3  https://olympics.com/en/paris-2024/sports/archery
4  https://olympics.com/en/paris-2024/sports/archery


File: schedules.csv
Columns: ['start_date', 'end_date', 'day', 'status', 'discipline', 'discipline_code', 'event', 'event_medal', 'phase', 'gender', 'event_type', 'venue', 'venue_code', 'location_description', 'location_code', 'url']
First 5 rows:
                  start_date                   end_date         day    status  \
0  2024-07-24T15:00:00+02:00  2024-07-24T16:45:00+02:00  2024-07-24  FINISHED
1  2024-07-24T15:00:00+02:00  2024-07-24T16:45:00+02:00  2024-07-24  FINISHED
2  2024-07-24T15:30:00+02:00  2024-07-24T15:46:00+02:00  2024-07-24  FINISHED
3  2024-07-24T16:00:00+02:00  2024-07-24T16:16:00+02:00  2024-07-24  FINISHED
4  2024-07-24T16:30:00+02:00  2024-07-24T16:46:00+02:00  2024-07-24  FINISHED

     discipline discipline_code event  event_medal          phase gender  \
0      Football             FBL   Men            0  Men's Group B      M
1      Football             FBL   Men            0  Men's Group C      M
2  Rugby Sevens             RU7   Men            0   Men's Pool B      M
3  Rugby Sevens             RU7   Men            0   Men's Pool B      M
4  Rugby Sevens             RU7   Men            0   Men's Pool C      M

  event_type                      venue venue_code  \
0      HTEAM  Geoffroy-Guichard Stadium        STE
1      HTEAM           Parc des Princes        PDP
2      HTEAM            Stade de France        STA
3      HTEAM            Stade de France        STA
4      HTEAM            Stade de France        STA

                       location_description location_code  \
0  Geoffroy-Guichard Stadium, Saint-Etienne           STE
1                   Parc des Princes, Paris           PDP
2                           Stade de France           STA
3                           Stade de France           STA
4                           Stade de France           STA

                                                 url
0   /en/paris-2024/results/football/men/gpb-000100--
1   /en/paris-2024/results/football/men/gpc-000100--
2  /en/paris-2024/results/rugby-sevens/men/gpb-00...
3  /en/paris-2024/results/rugby-sevens/men/gpb-00...
4  /en/paris-2024/results/rugby-sevens/men/gpc-00...


File: teams.csv
Columns: ['code', 'current', 'team', 'team_gender', 'country_code', 'country', 'country_long', 'discipline', 'disciplines_code', 'events', 'athletes', 'coaches', 'athletes_codes', 'num_athletes', 'coaches_codes', 'num_coaches']
First 5 rows:
                code  current                        team team_gender  \
0  ARCMTEAM3---CHN01     True  People's Republic of China           M
1  ARCMTEAM3---COL01     True                    Colombia           M
2  ARCMTEAM3---FRA01     True                      France           M
3  ARCMTEAM3---GBR01     True               Great Britain           M
4  ARCMTEAM3---IND01     True                       India           M

  country_code        country                country_long discipline  \
0          CHN          China  People's Republic of China    Archery
1          COL       Colombia                    Colombia    Archery
2          FRA         France                      France    Archery
3          GBR  Great Britain               Great Britain    Archery
4          IND          India                       India    Archery

  disciplines_code      events  \
0              ARC  Men's Team
1              ARC  Men's Team
2              ARC  Men's Team
3              ARC  Men's Team
4              ARC  Men's Team

                                            athletes coaches  \
0        ['KAO Wenchao', 'LI Zhongyuan', 'WANG Yan']     NaN
1  ['ARCILA Santiago', 'ENRIQUEZ Jorge', 'HERNAND...     NaN
2  ['ADDIS Baptiste', 'CHIRAULT Thomas', 'VALLADO...     NaN
3            ['HALL Conor', 'HALL Tom', 'WISE Alex']     NaN
4  ['BOMMADEVARA Dhiraj', 'JADHAV Pravin Ramesh',...     NaN

                      athletes_codes  num_athletes coaches_codes  num_coaches
0  ['1913366', '1913367', '1913369']           3.0           NaN          NaN
1  ['1935642', '1543412', '1935644']           3.0           NaN          NaN
2  ['1541270', '1541272', '1541275']           3.0           NaN          NaN
3  ['1560988', '1560989', '1561003']           3.0           NaN          NaN
4  ['1546108', '1546112', '1546110']           3.0           NaN          NaN


File: technical_officials.csv
Columns: ['code', 'current', 'name', 'gender', 'function', 'category', 'organisation_code', 'organisation', 'organisation_long', 'disciplines', 'birth_date']
First 5 rows:
      code  current                name  gender function category  \
0  1536406     True  FRATINI Elisabetta  Female  Referee        J
1  1550583     True         ILIC Corina  Female  Referee        J
2  1550593     True          MAAFI Ziad    Male  Referee        J
3  1550642     True         FUMEA Maria  Female    Judge        J
4  1550643     True         LEUNG Li Li  Female    Judge        J

  organisation_code organisation                    organisation_long  \
0               ITA        Italy                                Italy
1               CRO      Croatia                              Croatia
2               ALG      Algeria                              Algeria
3               FIG          FIG  International Gymnastics Federation
4               FIG          FIG  International Gymnastics Federation

                                         disciplines birth_date
0                                           ['Judo']        NaN
1                                           ['Judo']        NaN
2                                           ['Judo']        NaN
3  ['Artistic Gymnastics', 'Rhythmic Gymnastics',...        NaN
4  ['Artistic Gymnastics', 'Rhythmic Gymnastics',...        NaN


File: torch_route.csv
Columns: ['title', 'city', 'date_start', 'date_end', 'tag', 'url', 'stage_number']
First 5 rows:
                        title       city            date_start  \
0           Lighting Ceremony    Olympia  2024-04-15T22:01:00Z
1             Relay in Greece        NaN  2024-04-16T10:02:00Z
2           Handover Ceremony     Athens  2024-04-25T22:01:00Z
3  Crossing the Mediterranean  Marseille  2024-04-26T17:08:00Z
4                    Prologue  Marseille  2024-05-07T22:02:00Z

               date_end                     tag  \
0  2024-04-16T10:01:00Z       lighting-ceremony
1  2024-04-26T17:06:00Z         relay-in-greece
2  2024-04-26T17:07:00Z       handover-ceremony
3  2024-05-07T22:01:00Z  mediterranean-crossing
4  2024-05-08T20:02:00Z      prologue-marseille

                                                 url  stage_number
0  https://olympics.com/en/paris-2024/olympic-tor...           NaN
1  https://olympics.com/en/paris-2024/olympic-tor...           NaN
2  https://olympics.com/en/paris-2024/olympic-tor...           NaN
3  https://olympics.com/en/paris-2024/olympic-tor...           NaN
4  https://olympics.com/en/paris-2024/olympic-tor...           NaN


File: venues.csv
Columns: ['venue', 'sports', 'date_start', 'date_end', 'tag', 'url']
First 5 rows:
                   venue                                             sports  \

File: 3x3 Basketball.csv
Columns: ['date', 'stage_code', 'event_code', 'event_name', 'event_stage', 'stage', 'gender', 'discipline_name', 'discipline_code', 'venue', 'participant_code', 'participant_name', 'participant_type', 'participant_country_code', 'participant_country', 'result', 'result_type', 'result_WLT', 'start_order']
First 5 rows:
                        date                          stage_code event_code  \
0  2024-07-30T18:59:05+02:00  BK3MTEAM3-------------GPA-000100--  BK3MTEAM3
1  2024-07-30T18:59:05+02:00  BK3MTEAM3-------------GPA-000100--  BK3MTEAM3
2  2024-07-30T19:26:55+02:00  BK3MTEAM3-------------GPA-000200--  BK3MTEAM3
3  2024-07-30T19:26:55+02:00  BK3MTEAM3-------------GPA-000200--  BK3MTEAM3
4  2024-07-30T22:30:21+02:00  BK3MTEAM3-------------GPA-000300--  BK3MTEAM3

  event_name       event_stage       stage gender discipline_name  \
0        Men  Men's Pool Round  Pool Round      M  3x3 Basketball
1        Men  Men's Pool Round  Pool Round      M  3x3 Basketball
2        Men  Men's Pool Round  Pool Round      M  3x3 Basketball
3        Men  Men's Pool Round  Pool Round      M  3x3 Basketball
4        Men  Men's Pool Round  Pool Round      M  3x3 Basketball

  discipline_code          venue   participant_code  \
0             BK3  La Concorde 1  BK3MTEAM3---LAT01
1             BK3  La Concorde 1  BK3MTEAM3---LTU01
2             BK3  La Concorde 1  BK3MTEAM3---CHN01
3             BK3  La Concorde 1  BK3MTEAM3---NED01
4             BK3  La Concorde 1  BK3MTEAM3---POL01

             participant_name participant_type participant_country_code  \
0                      Latvia             Team                      LAT
1                   Lithuania             Team                      LTU
2  People's Republic of China             Team                      CHN
3                 Netherlands             Team                      NED
4                      Poland             Team                      POL

  participant_country  result result_type result_WLT  start_order
0              Latvia      21      POINTS          W            1
1           Lithuania      14      POINTS          L            2
2               China      16      POINTS          L            1
3         Netherlands      21      POINTS          W            2
4              Poland      19      POINTS          L            1


File: Archery.csv
Columns: ['date', 'stage_code', 'event_code', 'event_name', 'event_stage', 'stage', 'gender', 'discipline_name', 'discipline_code', 'venue', 'participant_code', 'participant_name', 'participant_type', 'participant_country_code', 'participant_country', 'rank', 'result', 'result_type', 'result_WLT', 'qualification_mark', 'start_order', 'bib']
First 5 rows:
                        date                          stage_code   event_code  \
0  2024-07-25T16:35:29+02:00  ARCMINDIVID-----------QUAL000100--  ARCMINDIVID
1  2024-07-25T16:35:29+02:00  ARCMINDIVID-----------QUAL000100--  ARCMINDIVID
2  2024-07-25T16:35:29+02:00  ARCMINDIVID-----------QUAL000100--  ARCMINDIVID
3  2024-07-25T16:35:29+02:00  ARCMINDIVID-----------QUAL000100--  ARCMINDIVID
4  2024-07-25T16:35:29+02:00  ARCMINDIVID-----------QUAL000100--  ARCMINDIVID

         event_name                     event_stage          stage gender  \
0  Men's Individual  Men's Individual Ranking Round  Ranking Round      M
1  Men's Individual  Men's Individual Ranking Round  Ranking Round      M
2  Men's Individual  Men's Individual Ranking Round  Ranking Round      M
3  Men's Individual  Men's Individual Ranking Round  Ranking Round      M
4  Men's Individual  Men's Individual Ranking Round  Ranking Round      M

  discipline_name discipline_code      venue  ... participant_type  \
0         Archery             ARC  Invalides  ...           Person
1         Archery             ARC  Invalides  ...           Person
2         Archery             ARC  Invalides  ...           Person
3         Archery             ARC  Invalides  ...           Person
4         Archery             ARC  Invalides  ...           Person

  participant_country_code participant_country rank result  result_type  \
0                      KOR               Korea  1.0    686       POINTS
1                      KOR               Korea  2.0    682       POINTS
2                      GER             Germany  3.0    681       POINTS
3                      IND               India  4.0    681       POINTS
4                      KOR               Korea  5.0    681       POINTS

   result_WLT qualification_mark start_order  bib
0         NaN                NaN           8   4B
1         NaN                NaN          10   5B
2         NaN                NaN          37  19A
3         NaN                NaN          24  12B
4         NaN                NaN          12   6B

[5 rows x 22 columns]


File: Artistic Gymnastics.csv
Columns: ['date', 'stage_code', 'event_code', 'event_name', 'event_stage', 'stage', 'gender', 'discipline_name', 'discipline_code', 'venue', 'participant_code', 'participant_name', 'participant_type', 'participant_country_code', 'participant_country', 'rank', 'result', 'result_type', 'result_diff', 'start_order', 'bib']
First 5 rows:
                        date                          stage_code event_code  \
0  2024-07-31T20:13:54+02:00  GARM1AA---------------FNL-000001--    GARM1AA
1  2024-07-31T20:13:54+02:00  GARM1AA---------------FNL-000001--    GARM1AA
2  2024-07-31T20:13:54+02:00  GARM1AA---------------FNL-000001--    GARM1AA
3  2024-07-31T20:13:54+02:00  GARM1AA---------------FNL-000001--    GARM1AA
4  2024-07-31T20:13:54+02:00  GARM1AA---------------FNL-000001--    GARM1AA

         event_name             event_stage  stage gender  \
0  Men's All-Around  Men's All-Around Final  Final      M
1  Men's All-Around  Men's All-Around Final  Final      M
2  Men's All-Around  Men's All-Around Final  Final      M
3  Men's All-Around  Men's All-Around Final  Final      M
4  Men's All-Around  Men's All-Around Final  Final      M

       discipline_name discipline_code        venue  ...     participant_name  \
0  Artistic Gymnastics             GAR  Bercy Arena  ...          DUNKEL Nils
1  Artistic Gymnastics             GAR  Bercy Arena  ...         RIJKEN Frank
2  Artistic Gymnastics             GAR  Bercy Arena  ...          DOLCI Felix
3  Artistic Gymnastics             GAR  Bercy Arena  ...  LANGENEGGER Florian
4  Artistic Gymnastics             GAR  Bercy Arena  ...         SOARES Diogo

  participant_type participant_country_code participant_country rank  result  \
0           Person                      GER             Germany  NaN  13.700
1           Person                      NED         Netherlands  NaN  13.733
2           Person                      CAN              Canada  NaN  14.366
3           Person                      SUI         Switzerland  NaN  14.133
4           Person                      BRA              Brazil  NaN  14.500

   result_type result_diff  start_order    bib
0       POINTS         NaN          1.0  139.0
1       POINTS         NaN          2.0  168.0
2       POINTS         NaN          3.0  112.0
3       POINTS         NaN          4.0  174.0
4       POINTS         NaN          5.0  108.0

[5 rows x 21 columns]


File: Artistic Swimming.csv
Columns: ['date', 'stage_code', 'event_code', 'event_name', 'event_stage', 'stage', 'gender', 'discipline_name', 'discipline_code', 'venue', 'participant_code', 'participant_name', 'participant_type', 'participant_country_code', 'participant_country', 'rank', 'result', 'result_type', 'result_IRM', 'result_diff', 'start_order']
First 5 rows:
                        date                          stage_code event_code  \
0  2024-08-09T22:54:54+02:00  SWAWTEAM2-------------FNL-000200--  SWAWTEAM2
1  2024-08-09T22:54:54+02:00  SWAWTEAM2-------------FNL-000200--  SWAWTEAM2
2  2024-08-09T22:54:54+02:00  SWAWTEAM2-------------FNL-000200--  SWAWTEAM2
3  2024-08-09T22:54:54+02:00  SWAWTEAM2-------------FNL-000200--  SWAWTEAM2
4  2024-08-09T22:54:54+02:00  SWAWTEAM2-------------FNL-000200--  SWAWTEAM2

  event_name             event_stage              stage gender  \
0       Duet  Duet Technical Routine  Technical Routine      W
1       Duet  Duet Technical Routine  Technical Routine      W
2       Duet  Duet Technical Routine  Technical Routine      W
3       Duet  Duet Technical Routine  Technical Routine      W
4       Duet  Duet Technical Routine  Technical Routine      W

     discipline_name discipline_code            venue  ...  \
0  Artistic Swimming             SWA  Aquatics Centre  ...
1  Artistic Swimming             SWA  Aquatics Centre  ...
2  Artistic Swimming             SWA  Aquatics Centre  ...
3  Artistic Swimming             SWA  Aquatics Centre  ...
4  Artistic Swimming             SWA  Aquatics Centre  ...

             participant_name participant_type participant_country_code  \
0  People's Republic of China             Team                      CHN
1                     Austria             Team                      AUT
2                 Netherlands             Team                      NED
3               Great Britain             Team                      GBR
4                     Ukraine             Team                      UKR

  participant_country rank    result  result_type result_IRM result_diff  \
0               China  1.0  276.7867       POINTS        NaN         NaN
1             Austria  2.0  267.2533       POINTS        NaN      9.5334
2         Netherlands  3.0  264.7066       POINTS        NaN     12.0801
3       Great Britain  4.0  264.0282       POINTS        NaN     12.7585
4             Ukraine  5.0  260.4600       POINTS        NaN     16.3267

   start_order
0         18.0
1          9.0
2         15.0
3         17.0
4         10.0

[5 rows x 21 columns]


File: Athletics.csv
Columns: ['date', 'stage_code', 'event_code', 'event_name', 'event_stage', 'stage', 'gender', 'discipline_name', 'discipline_code', 'venue', 'participant_code', 'participant_name', 'participant_type', 'participant_country_code', 'participant_country', 'rank', 'result', 'result_type', 'result_IRM', 'result_diff', 'qualification_mark', 'start_order', 'bib']
First 5 rows:
                        date                          stage_code  event_code  \
0  2024-08-03T17:48:06+02:00  ATHX4X400M------------RND1000200--  ATHX4X400M
1  2024-08-03T17:48:06+02:00  ATHX4X400M------------RND1000200--  ATHX4X400M
2  2024-08-03T17:48:06+02:00  ATHX4X400M------------RND1000200--  ATHX4X400M
3  2024-08-03T17:48:06+02:00  ATHX4X400M------------RND1000200--  ATHX4X400M
4  2024-08-03T17:48:06+02:00  ATHX4X400M------------RND1000200--  ATHX4X400M

             event_name                            event_stage  \
0  4 x 400m Relay Mixed  4 x 400m Relay Mixed Round 1 - Heat 2
1  4 x 400m Relay Mixed  4 x 400m Relay Mixed Round 1 - Heat 2
2  4 x 400m Relay Mixed  4 x 400m Relay Mixed Round 1 - Heat 2
3  4 x 400m Relay Mixed  4 x 400m Relay Mixed Round 1 - Heat 2
4  4 x 400m Relay Mixed  4 x 400m Relay Mixed Round 1 - Heat 2

              stage gender discipline_name discipline_code            venue  \
0  Round 1 - Heat 2      X       Athletics             ATH  Stade de France
1  Round 1 - Heat 2      X       Athletics             ATH  Stade de France
2  Round 1 - Heat 2      X       Athletics             ATH  Stade de France
3  Round 1 - Heat 2      X       Athletics             ATH  Stade de France
4  Round 1 - Heat 2      X       Athletics             ATH  Stade de France

   ... participant_country_code participant_country rank   result result_type  \
0  ...                      GBR       Great Britain  1.0  3:10.61        TIME
1  ...                      NED         Netherlands  2.0  3:10.81        TIME
2  ...                      ITA               Italy  3.0  3:11.59        TIME
3  ...                      NGR             Nigeria  4.0  3:11.99        TIME
4  ...                      IRL             Ireland  5.0  3:12.67        TIME

   result_IRM result_diff qualification_mark start_order bib
0         NaN         NaN                  Q         4.0 NaN
1         NaN         NaN                  Q         6.0 NaN
2         NaN         NaN                  Q         3.0 NaN
3         NaN         NaN                NaN         5.0 NaN
4         NaN         NaN                NaN         7.0 NaN

[5 rows x 23 columns]


File: Badminton.csv
Columns: ['date', 'stage_code', 'event_code', 'event_name', 'event_stage', 'stage', 'gender', 'discipline_name', 'discipline_code', 'venue', 'participant_code', 'participant_name', 'participant_type', 'participant_country_code', 'participant_country', 'result', 'result_type', 'result_WLT', 'result_IRM']
First 5 rows:
                        date                          stage_code   event_code  \
0  2024-07-27T10:00:05+02:00  BDMMDOUBLES-----------GPA-000100--  BDMMDOUBLES
1  2024-07-27T10:00:05+02:00  BDMMDOUBLES-----------GPA-000100--  BDMMDOUBLES
2  2024-07-27T11:42:25+02:00  BDMMDOUBLES-----------GPA-000200--  BDMMDOUBLES
3  2024-07-27T11:42:25+02:00  BDMMDOUBLES-----------GPA-000200--  BDMMDOUBLES
4  2024-07-27T15:28:34+02:00  BDMMDOUBLES-----------GPC-000200--  BDMMDOUBLES

      event_name                               event_stage  \
0  Men's Doubles  Men's Doubles Group Play Stage - Group A
1  Men's Doubles  Men's Doubles Group Play Stage - Group A
2  Men's Doubles  Men's Doubles Group Play Stage - Group A
3  Men's Doubles  Men's Doubles Group Play Stage - Group A
4  Men's Doubles  Men's Doubles Group Play Stage - Group C

                        stage gender discipline_name discipline_code  \
0  Group Play Stage - Group A      M       Badminton             BDM
1  Group Play Stage - Group A      M       Badminton             BDM
2  Group Play Stage - Group A      M       Badminton             BDM
3  Group Play Stage - Group A      M       Badminton             BDM
4  Group Play Stage - Group C      M       Badminton             BDM

               venue   participant_code  \
0  La Chapelle Arena  BDMMDOUBLES-CHN02
1  La Chapelle Arena  BDMMDOUBLES-CAN01
2  La Chapelle Arena  BDMMDOUBLES-MAS01
3  La Chapelle Arena  BDMMDOUBLES-GBR01
4  La Chapelle Arena  BDMMDOUBLES-INA01

                        participant_name participant_type  \
0            LIANG Wei Keng / WANG Chang             Team
1                 DONG Adam / YAKURA Nyl             Team
2              CHIA Aaron / SOH Wooi Yik             Team
3                  LANE Ben / VENDY Sean             Team
4  ALFIAN Fajar / ARDIANTO Muhammad Rian             Team

  participant_country_code participant_country  result result_type result_WLT  \
0                      CHN               China       2      POINTS          W
1                      CAN              Canada       0      POINTS          L
2                      MAS            Malaysia       2      POINTS          W
3                      GBR       Great Britain       1      POINTS          L
4                      INA           Indonesia       2      POINTS          W

  result_IRM
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN


File: Basketball.csv
Columns: ['date', 'stage_code', 'event_code', 'event_name', 'event_stage', 'stage', 'gender', 'discipline_name', 'discipline_code', 'venue', 'participant_code', 'participant_name', 'participant_type', 'participant_country_code', 'participant_country', 'result', 'result_type', 'result_WLT', 'start_order']
First 5 rows:
                        date                          stage_code event_code  \
0  2024-07-27T12:56:50+02:00  BKBMTEAM5-------------GPA-000100--  BKBMTEAM5
1  2024-07-27T12:56:50+02:00  BKBMTEAM5-------------GPA-000100--  BKBMTEAM5
2  2024-07-27T15:13:15+02:00  BKBMTEAM5-------------GPB-000100--  BKBMTEAM5
3  2024-07-27T15:13:15+02:00  BKBMTEAM5-------------GPB-000100--  BKBMTEAM5
4  2024-07-27T19:20:21+02:00  BKBMTEAM5-------------GPB-000200--  BKBMTEAM5

  event_name                  event_stage                  stage gender  \
0        Men  Men's Group Phase - Group A  Group Phase - Group A      M
1        Men  Men's Group Phase - Group A  Group Phase - Group A      M
2        Men  Men's Group Phase - Group B  Group Phase - Group B      M
3        Men  Men's Group Phase - Group B  Group Phase - Group B      M
4        Men  Men's Group Phase - Group B  Group Phase - Group B      M

  discipline_name discipline_code                  venue   participant_code  \
0      Basketball             BKB  Pierre Mauroy Stadium  BKBMTEAM5---AUS01
1      Basketball             BKB  Pierre Mauroy Stadium  BKBMTEAM5---ESP01
2      Basketball             BKB  Pierre Mauroy Stadium  BKBMTEAM5---GER01
3      Basketball             BKB  Pierre Mauroy Stadium  BKBMTEAM5---JPN01
4      Basketball             BKB  Pierre Mauroy Stadium  BKBMTEAM5---FRA01

  participant_name participant_type participant_country_code  \
0        Australia             Team                      AUS
1            Spain             Team                      ESP
2          Germany             Team                      GER
3            Japan             Team                      JPN
4           France             Team                      FRA

  participant_country  result result_type result_WLT  start_order
0           Australia      92      POINTS          W            1
1               Spain      80      POINTS          L            2
2             Germany      97      POINTS          W            1
3               Japan      77      POINTS          L            2
4              France      78      POINTS          W            1


File: Beach Volleyball.csv
Columns: ['date', 'stage_code', 'event_code', 'event_name', 'event_stage', 'stage', 'gender', 'discipline_name', 'discipline_code', 'venue', 'participant_code', 'participant_name', 'participant_type', 'participant_country_code', 'participant_country', 'result', 'result_type', 'result_WLT', 'result_IRM', 'start_order']
First 5 rows:
                        date                          stage_code event_code  \
0  2024-07-27T14:46:36+02:00  VBVMTEAM2-------------GPD-000100--  VBVMTEAM2
1  2024-07-27T14:46:36+02:00  VBVMTEAM2-------------GPD-000100--  VBVMTEAM2
2  2024-07-27T15:46:23+02:00  VBVMTEAM2-------------GPA-000100--  VBVMTEAM2
3  2024-07-27T15:46:23+02:00  VBVMTEAM2-------------GPA-000100--  VBVMTEAM2
4  2024-07-27T19:55:43+02:00  VBVMTEAM2-------------GPD-000200--  VBVMTEAM2

  event_name                       event_stage                       stage  \
0        Men  Men's Preliminary Phase - Pool D  Preliminary Phase - Pool D
1        Men  Men's Preliminary Phase - Pool D  Preliminary Phase - Pool D
2        Men  Men's Preliminary Phase - Pool A  Preliminary Phase - Pool A
3        Men  Men's Preliminary Phase - Pool A  Preliminary Phase - Pool A
4        Men  Men's Preliminary Phase - Pool D  Preliminary Phase - Pool D

  gender   discipline_name discipline_code                 venue  \
0      M  Beach Volleyball             VBV  Eiffel Tower Stadium
1      M  Beach Volleyball             VBV  Eiffel Tower Stadium
2      M  Beach Volleyball             VBV  Eiffel Tower Stadium
3      M  Beach Volleyball             VBV  Eiffel Tower Stadium
4      M  Beach Volleyball             VBV  Eiffel Tower Stadium

    participant_code      participant_name participant_type  \
0  VBVMTEAM2---USA01        Partain/Benesh             Team
1  VBVMTEAM2---CUB01            Diaz/Alayo             Team
2  VBVMTEAM2---SWE01         Ahman/Hellvig             Team
3  VBVMTEAM2---AUS02  Nicolaidis/Carracher             Team
4  VBVMTEAM2---BRA01          George/Andre             Team

  participant_country_code participant_country  result result_type result_WLT  \
0                      USA       United States       0      POINTS          L
1                      CUB                Cuba       2      POINTS          W
2                      SWE              Sweden       2      POINTS          W
3                      AUS           Australia       0      POINTS          L

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11165 entries, 0 to 11164
Data columns (total 48 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   code                  11165 non-null  object
 1   current               11165 non-null  bool
 2   name_athlete          11165 non-null  object
 3   name_short            11162 non-null  object
 4   name_tv               11162 non-null  object
 5   gender_athlete        11165 non-null  object
 6   function              11165 non-null  object
 7   country_code_athlete  11165 non-null  object
 8   country_athlete       11165 non-null  object
 9   country_long_athlete  11165 non-null  object
 10  nationality           11162 non-null  object
 11  nationality_long      11162 non-null  object
 12  nationality_code      11162 non-null  object
 13  height                11162 non-null  float64
 14  weight                11160 non-null  float64
 15  disciplines           11165 non-null  object
 16  events                11165 non-null  object
 17  birth_date            11165 non-null  datetime64[ns]
 18  birth_place           8776 non-null   object
 19  birth_country         9526 non-null   object
 20  residence_place       6849 non-null   object
 21  residence_country     8337 non-null   object
 22  nickname              2992 non-null   object
 23  hobbies               4247 non-null   object
 24  occupation            9633 non-null   object
 25  education             5572 non-null   object
 26  family                5601 non-null   object
 27  lang                  10657 non-null  object
 28  coach                 8272 non-null   object
 29  reason                5887 non-null   object
 30  hero                  3349 non-null   object
 31  influence             2167 non-null   object
 32  philosophy            2818 non-null   object
 33  sporting_relatives    2538 non-null   object
 34  ritual                873 non-null    object
 35  other_sports          1065 non-null   object
 36  medal_type            760 non-null    object
 37  medal_code            759 non-null    float64
 38  medal_date            760 non-null    object
 39  name_medal            760 non-null    object
 40  gender_medal          760 non-null    object
 41  discipline            760 non-null    object
 42  event                 760 non-null    object
 43  event_type            760 non-null    object
 44  url_event             754 non-null    object
 45  country_code_medal    760 non-null    object
 46  country_medal         760 non-null    object
 47  country_long_medal    760 non-null    object
dtypes: bool(1), datetime64[ns](1), float64(3), object(43)
memory usage: 4.0+ MB
None

ValueError: You are trying to merge on int64 and object columns for key 'code'. If you wish to proceed you should use pd.concat